// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBinHkr_7nOrSExEQ3XQRe6PjjWbp-M7ds',
    appId: '1:319254190312:web:55f430229d35f1fae4115d',
    messagingSenderId: '319254190312',
    projectId: 'chatapp-f46ab',
    authDomain: 'chatapp-f46ab.firebaseapp.com',
    storageBucket: 'chatapp-f46ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uIl6Pk8ft0dYLykH2S_qd5WO9s-vLRc',
    appId: '1:319254190312:android:00d3be2909537561e4115d',
    messagingSenderId: '319254190312',
    projectId: 'chatapp-f46ab',
    storageBucket: 'chatapp-f46ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkUA45tMHJWXeK6TgAu7HySRm38TGdK4',
    appId: '1:319254190312:ios:cbb4823665882d96e4115d',
    messagingSenderId: '319254190312',
    projectId: 'chatapp-f46ab',
    storageBucket: 'chatapp-f46ab.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkUA45tMHJWXeK6TgAu7HySRm38TGdK4',
    appId: '1:319254190312:ios:cbb4823665882d96e4115d',
    messagingSenderId: '319254190312',
    projectId: 'chatapp-f46ab',
    storageBucket: 'chatapp-f46ab.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBinHkr_7nOrSExEQ3XQRe6PjjWbp-M7ds',
    appId: '1:319254190312:web:7adf57943968c91ce4115d',
    messagingSenderId: '319254190312',
    projectId: 'chatapp-f46ab',
    authDomain: 'chatapp-f46ab.firebaseapp.com',
    storageBucket: 'chatapp-f46ab.appspot.com',
  );
}
